### ISSUE TITLE
Your domain (choco.wtf) has expired.

### ISSUE THREAD

**Issue by RealTriassic** [2008Choco/Networking#1]
It appears that the domain used to host the libraries has expired making them inaccessible. The solution would be to either renew the domain or move to something like Maven Central.

![image](https://github.com/user-attachments/assets/6c3bc97c-0b7d-4d7d-9b82-da9e65faa8b2)

**Comment by RealTriassic** [comment]
![image](https://github.com/user-attachments/assets/42e3aaa9-b194-4fb9-9501-adaa6e530487)

**Comment by 2008Choco** [comment]
Thank you for letting me know! Apparently it expired in July and I wasn't notified of it, which is nice. I'll get this renewed soon.

**Comment by 2008Choco** [comment]
I've renewed this now and it should be good to go! Thanks!
